### ISSUE TITLE
stylelint-config-wordpress@9.0.0 requires a peer of stylelint@^7.2.0 but none was installed.

### ISSUE THREAD

**Issue by HeikoMamerow** [ntwb/stylelint-config-wordpress#95]
Hi, 
i am unable to install the plugin because:

> stylelint-config-wordpress@9.0.0 requires a peer of stylelint@^7.2.0 but none was installed.

But i use stylelint@7.3.1

![screenshot from 2016-09-27 12-30-58](https://cloud.githubusercontent.com/assets/1729487/18869877/95e80d7c-84ae-11e6-8e05-ec45d6a3e627.png)

Any tip? :-)

**Comment by ntwb** [comment]
Thanks @HeikoMamerow, for the most part you can ignore this message, it should work without performing the below, but it's probably best to do this anyway.

It's because of a weird issue with how NPM installs, or in this case no longer installs peer dependencies, when installing packages globally that depend upon one another they need to be installed at the same time /shrug

So, if you run: `npm uninstall -g stylelint stylelint-config-wordpress` and follow that up by running  `npm install -g stylelint stylelint-config-wordpress` both packages should be installed without error.

**Comment by HeikoMamerow** [comment]
Ha, works like charme! Thank you!!!!! :-)
